# -*- coding: utf-8 -*-
""" A function library for massaging ADC data generated by PWM. """
import numpy as np


def get_minima(a):
    """ Returns the indexes of the first and last minimum values in an array. """
    i = [45]    # []
    pwm_period = 0.0015
    sample_size = 8
    wave_length = round(a['sample_rate_khz'] * a['ring_size'] * pwm_period)
    sample_length = round(sample_size * wave_length)
    i.append(int(i[0] + sample_length))
    return i


def get_voltage(f):
    """ Converts ADC native units (1/255) to volts. """
    return f * 5


def get_firing_time(pwm_period=0.0015, sample_size=7):
    """ Returns laser firing time. """
    return sample_size * pwm_period
